import {api,esc,form,notice,upload,navigation,download} from './platform-client.js';
import {fields,needs,progress,state} from './dossier.js';
const A=window.__adv,p=window.MEET_PROFILE;let recorderDone=Promise.resolve(),resolveRecorder=null;
let dossier=null,call=null,saving=false,warning='',list=[],pendingSegments=[],audioBuffers=[],audioBytes=0,audioRun=Date.now(),audioOffset=0,audioSequence=0,draining=false;
const panel=document.createElement('details');panel.id='cloudPanel';panel.innerHTML='<summary>Dossier partagé & documents</summary><div id="cloudBody"></div>';document.body.append(panel);
const header=document.createElement('header');header.innerHTML=navigation(p);document.body.prepend(header);header.querySelector('#logout').onclick=async()=>{if(A.S.listening){warning='Terminez ou sauvegardez l’appel avant la déconnexion.';render();return;}await api('logout',{});location.assign('/login');};
A.S.cfg.advisor=p.name;document.getElementById('advisorName').value=p.name;document.getElementById('advisorName').readOnly=true;
// IndexedDB is a retry buffer only. The server remains the shared source of truth.
const dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open('meet-upload-queue',1);r.onupgradeneeded=()=>r.result.createObjectStore('pending',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function queue(action,value){const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('pending',action==='getAll'?'readonly':'readwrite'),s=tx.objectStore('pending'),r=action==='getAll'?s.getAll():s[action](action==='put'?{enqueuedAt:Date.now(),...value}:value);let result;r.onsuccess=()=>result=r.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);});}
async function drain(){if(draining)return;draining=true;try{for(const item of (await queue('getAll')).sort((a,b)=>Number(a.type==='finish')-Number(b.type==='finish')||(a.enqueuedAt||0)-(b.enqueuedAt||0))){if(item.userId!==p.id)continue;if(item.type==='audio'||item.type==='file')await upload(item.blob,item.dossierId,{callId:item.callId,kind:item.type==='audio'?'audio':'evidence',fileId:item.id,fieldId:item.fieldId,audioGroup:item.audioGroup,audioOffset:item.audioOffset});else if(item.type==='segments')await api('segments',{dossierId:item.dossierId,callId:item.callId,segments:item.segments});else if(item.type==='finish')await api('finish-call',{dossierId:item.dossierId,callId:item.callId,duration:item.duration,incomplete:item.incomplete});await queue('delete',item.id);}warning='';}catch(e){warning='Sauvegarde à reprendre : '+e.message;}finally{draining=false;render();}}
async function flushAudio(){if(!audioBytes||!call)return;const parts=audioBuffers;audioBuffers=[];audioBytes=0;const file=new File(parts,'audio-'+audioRun+'-'+String(audioSequence++).padStart(6,'0')+'.webm',{type:parts[0].type||'audio/webm'});await queue('put',{id:crypto.randomUUID(),userId:p.id,type:'audio',dossierId:dossier.id,callId:call.id,blob:file,audioGroup:String(audioRun),audioOffset});drain();}
async function flushSegments(){if(!pendingSegments.length||!call)return;const segments=pendingSegments.splice(0,50);await queue('put',{id:crypto.randomUUID(),userId:p.id,type:'segments',dossierId:dossier.id,callId:call.id,segments});drain();}
async function select(id){if(A.S.listening)throw new Error('Terminez l’appel avant de changer de dossier.');dossier=(await api('detail',null,{dossierId:id})).dossier;window.meetActiveDossier=dossier.id;A.resetDossierCall();A.S.cfg.advisor=p.name;document.getElementById('advisorName').value=p.name;A.restoreDossierCall({cfg:{...A.S.cfg,societe:dossier.society,advisor:p.name,contexte:dossier.name,consent:false},segments:[],facts:[],questions:[],resume:''});render();}
function render(){const data=dossier?.data,pr=data&&progress(data);const expanded=[...panel.querySelectorAll('details')].map(x=>x.open);document.getElementById('cloudBody').innerHTML='<p>Connecté : '+esc(p.name)+'. Données partagées selon vos affectations.</p><select id="cloudChoose"><option value="">Choisir un dossier attribué</option>'+list.map(d=>'<option value="'+d.id+'" '+(d.id===dossier?.id?'selected':'')+'>'+esc(d.name)+' — '+esc(d.society)+'</option>').join('')+'</select><button id="cloudNew">Nouveau dossier</button><button id="cloudRetry">Reprendre les envois</button>'+(data?'<h3>'+esc(dossier.name)+'</h3><p>'+pr.known+'/'+pr.total+' informations déclarées · '+pr.received+' pièces reçues · aucune validation automatique.</p><label>Objectif<select id="cloudStage">'+[['qualification','Qualification'],['documents','Compléter les documents'],['approfondir','Approfondir les points ouverts']].map(([v,l])=>'<option value="'+v+'" '+(data.stage===v?'selected':'')+'>'+l+'</option>').join('')+'</select></label><details><summary>Documents ciblés</summary>'+[...new Set(fields.flatMap(f=>f.sources.map(s=>s.model)))].map(m=>'<label><input type="checkbox" data-target="'+m+'" '+(data.targets.includes(m)?'checked':'')+'>'+m+'</label>').join('')+'</details><details><summary>Questions documentaires</summary>'+needs(data,A.S.categorie).slice(0,8).map(f=>'<article class="card"><p>'+esc(f.question)+'</p><small>Alimente '+f.sources.map(s=>esc(s.model)+' §'+esc(s.section)).join(', ')+'</small><p><button data-question="'+f.id+'">Afficher</button><button data-defer="'+f.id+'">Reporter / indisponible</button></p></article>').join('')+'</details><details><summary>Faits et corrections</summary>'+data.facts.slice(-20).reverse().map(f=>'<p>'+esc(f.raw)+' '+(f.superseded?'(historique)':'')+'<br><small>« '+esc(f.quote)+' » — '+esc(f.role)+'</small><button data-correct="'+f.id+'">Retenir la correction</button></p>').join('')+'</details><label>Pièce client<input id="cloudFile" type="file" accept=".pdf,.docx,.txt,.md"></label><button id="cloudExport">Exporter MD</button><label>Importer une sauvegarde locale dans ce dossier vide<input id="legacyImport" type="file" accept=".json"></label><button id="legacyLocal">Reprendre un ancien dossier de ce navigateur</button>':'<p>Choisissez un dossier. Le test audio et l’appel exigent une affectation autorisée.</p>')+'<p role="status">'+esc(warning)+'</p>';panel.querySelectorAll('details').forEach((x,i)=>x.open=expanded[i]||false);}
async function command(body){const d=await api('command',{...body,dossierId:dossier.id,revision:dossier.revision});dossier=d;render();}
panel.addEventListener('click',async e=>{try{const t=e.target;
 if(t.id==='cloudNew'){if(A.S.listening)throw new Error('Terminez l’appel avant de créer un dossier.');const v=await form('Nouveau dossier',[{name:'name',label:'Nom du client / projet',required:true},{name:'society',label:'Société : PWM ou ADM',value:p.societies[0],required:true},{name:'clientId',label:'Client existant : identifiant exact, facultatif'}]);if(v){const d=await api('create',v);list=(await api('list')).dossiers;await select(d.id);}}
 if(t.id==='cloudRetry')await drain();
 if(t.dataset.question){const f=fields.find(f=>f.id===t.dataset.question);A.showDossierQuestion(f);}
 if(t.dataset.defer){const v=await form('Suivi du point',[{name:'status',label:'Statut : deferred / unknown / unavailable / not_applicable',value:'deferred',required:true},{name:'reason',label:'Motif',required:true},{name:'owner',label:'Responsable'},{name:'due',label:'Échéance',type:'date'}]);if(v)await command({...v,command:'defer',fieldId:t.dataset.defer});}
 if(t.dataset.correct){const v=await form('Correction avec historique',[{name:'confirm',label:'Saisir CONFIRMER pour conserver ce fait comme correction',required:true}]);if(v?.confirm==='CONFIRMER')await command({command:'correct',factId:t.dataset.correct});}
 if(t.id==='cloudExport')location.assign('/api/platform?'+new URLSearchParams({action:'export',dossierId:dossier.id}));
 if(t.id==='legacyLocal'){const old=JSON.parse(localStorage.getItem('adv.dossiers.v1')||'{"items":[]}');if(!old.items?.length)throw new Error('Aucun dossier local trouvé. Importez un fichier JSON.');const v=await form('Import contrôlé — aucune fusion automatique',[{name:'index',label:old.items.map((d,i)=>(i+1)+': '+d.name).join(' / '),required:true}]);if(v){const original=old.items[Number(v.index)-1];if(!original)throw new Error('Choix invalide.');dossier=await api('import',{dossierId:dossier.id,data:original});render();}}
 }catch(e){warning=e.message;render();}});
panel.addEventListener('change',async e=>{try{const t=e.target;if(t.id==='cloudChoose')await select(t.value);if(t.id==='cloudStage')await command({command:'stage',stage:t.value});if(t.dataset.target){const targets=new Set(dossier.data.targets);t.checked?targets.add(t.dataset.target):targets.delete(t.dataset.target);await command({command:'targets',targets:[...targets]});}
 if(t.id==='cloudFile'){const blob=t.files[0];if(blob){await queue('put',{id:crypto.randomUUID(),userId:p.id,type:'file',dossierId:dossier.id,blob});await drain();}}
 if(t.id==='legacyImport'){const f=t.files[0];if(f.size>5000000)throw new Error('Sauvegarde trop volumineuse.');dossier=await api('import',{dossierId:dossier.id,data:JSON.parse(await f.text())});render();}
 }catch(e){warning=e.message;render();}});
window.dossierEnsure=async()=>{if(!dossier)throw new Error('Choisissez ou créez un dossier attribué avant l’appel.');call=await api('start-call',{dossierId:dossier.id,callId:crypto.randomUUID(),config:A.S.cfg});};
window.dossierContext=()=>dossier?{stage:dossier.data.stage,needs:needs(dossier.data,A.S.categorie).slice(0,8),declared:dossier.data.facts.filter(f=>!f.superseded).slice(-15),deferred:dossier.data.actions}:null;
window.dossierFinalSegment=s=>{if(!call)return;const who=A.whoOf(s.sp);pendingSegments.push({...s,role:who==='me'?'advisor':who==='them'?'client':'uncertain'});flushSegments().catch(e=>{warning=e.message;render();});};
window.meetAudioChunk=blob=>{if(!call)return;audioBuffers.push(blob);audioBytes+=blob.size;if(audioBytes>1000000)flushAudio().catch(e=>{warning=e.message;render();});};
window.meetRecorderStarted=()=>{if(audioBytes)flushAudio().catch(e=>{warning=e.message;});audioRun=Date.now();audioOffset=A.S.elapsedMs+(A.S.listening?Date.now()-A.S.lastResume:0);audioSequence=0;recorderDone=new Promise(r=>resolveRecorder=r);};
window.meetRecorderStopped=()=>{resolveRecorder?.();resolveRecorder=null;};
window.dossierSaveCall=()=>{};
window.meetEndCall=async()=>{await Promise.race([recorderDone,new Promise(r=>setTimeout(r,3000))]);await flushSegments();await flushAudio();await queue('put',{id:crypto.randomUUID(),userId:p.id,type:'finish',dossierId:dossier.id,callId:call.id,duration:A.S.elapsedMs,incomplete:false});await drain();const pending=(await queue('getAll')).filter(x=>x.userId===p.id&&x.callId===call.id);return pending.length?'Sauvegarde incomplète : '+pending.length+' lot(s) restent sur cet appareil. Utilisez Reprendre les envois.':'Fragments audio et segments transmis sauvegardés. Bilan et documents en préparation côté serveur ; leur état est visible par le responsable.';};
setInterval(()=>{if(audioBytes)flushAudio().catch(e=>{warning=e.message;render();});drain();},6000);
setInterval(async()=>{if(!dossier||saving)return;saving=true;try{dossier=(await api('detail',null,{dossierId:dossier.id})).dossier;render();}catch(e){warning=e.message;render();}finally{saving=false;}},15000);
try{list=(await api('list')).dossiers;const id=new URLSearchParams(location.search).get('dossier');if(id)await select(id);else render();await drain();}catch(e){warning=e.message;render();}
