import {fields,uid,createDossier,ingest,state,needs,defer,correct,progress,draft,exportMarkdown,importDossier,event} from './dossier.js';
const modelNames={K09:'Évaluation préliminaire',K11:'Demande de documents',K13:'Connaissance du client',K15:'Contrôles de conformité',K16:'Résidences fiscales',K17:'Diligences',A06:'Sources et emplois',A07:'Résumé du projet',A02:'Trésorerie',A10:'Matrice des risques'};
const infoNames={unknown:'à recueillir',declared:'déclaré',clarify:'à préciser',conflict:'contradiction'};
const A=window.__adv, key='adv.dossiers.v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let db;try{db=JSON.parse(localStorage.getItem(key));}catch{}if(!db?.items)db={active:null,items:[]};
let current=()=>db.items.find(d=>d.id===db.active),busy=false,message='',selected='F01',retryAt=0,failures=0;
const root=document.createElement('details');root.id='dossierPanel';root.innerHTML='<summary>Dossier & documents</summary><div id="dossierBody"></div>';document.body.append(root);
const style=document.createElement('style');style.textContent='#dossierPanel{box-sizing:border-box;position:fixed;right:12px;bottom:12px;z-index:40;width:min(440px,calc(100vw - 24px));max-height:85vh;overflow:auto;background:#14232e;color:#e5edf3;border:1px solid #6b8599;border-radius:12px;padding:12px;box-shadow:0 8px 35px #0009}#dossierPanel summary{cursor:pointer;font-weight:700}#dossierPanel>summary{position:sticky;top:0;background:#14232e;padding:4px 0;z-index:1}#dossierBody button{background:#263d4b;color:#e5edf3;border:1px solid #6b8599;border-radius:6px;cursor:pointer}#dossierBody{font-size:13px}#dossierBody button,#dossierBody select,#dossierBody input{margin:4px 3px;padding:7px;max-width:100%}#dossierBody textarea{width:100%;min-height:70px}#dossierBody p{margin:10px 0}#dossierBody pre{white-space:pre-wrap}#dossierBody .fact{border-top:1px solid #536573;padding:8px 0}';document.head.append(style);

function ask(label,confirmation=false){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.style.cssText='background:#14232e;color:#e5edf3;max-width:90vw;border:1px solid #6b8599;border-radius:10px';dialog.innerHTML='<form method="dialog"><p>'+esc(label)+'</p>'+(confirmation?'':'<input aria-label="Réponse" autofocus style="width:100%;padding:8px">')+'<p><button value="ok">Confirmer</button> <button value="cancel">Annuler</button></p></form>';document.body.append(dialog);dialog.addEventListener('close',()=>{const value=dialog.returnValue==='ok'?(confirmation?'oui':dialog.querySelector('input').value):null;dialog.remove();resolve(value);});dialog.showModal();});}
const approve=async label=>!!(await ask(label,true));

function save(){try{localStorage.setItem(key,JSON.stringify(db));message='';}catch{message='Stockage plein : exportez le dossier maintenant.';}render();}
function download(name,text,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function render(){const opened=[...root.querySelectorAll('#dossierBody details')].map(x=>x.open);const focus=document.activeElement?.id;const d=current(),p=d&&progress(d),f=fields.find(f=>f.id===selected);document.getElementById('dossierBody').innerHTML=`
 <p>Données conservées sur ce navigateur. Exportez pour sauvegarder ou transférer. Aucune validation spécialisée disponible avec l’accès partagé.</p>
 <select id="dossierChoose"><option value="">Choisir un dossier</option>${db.items.map(x=>`<option value="${esc(x.id)}" ${x.id===db.active?'selected':''}>${esc(x.name)}</option>`).join('')}</select><button data-do="new">Nouveau dossier</button>
 <label>Importer une sauvegarde JSON <input id="dossierImport" type="file" accept=".json"></label>
 ${d?`<h3>${esc(d.name)}</h3><label>Objectif <select id="dossierStage">${[['qualification','Qualification'],['documents','Compléter les documents'],['approfondir','Approfondir les points ouverts']].map(([v,l])=>`<option value="${v}" ${d.stage===v?'selected':''}>${l}</option>`).join('')}</select></label>
 <p>Informations déclarées : ${p.total?p.known+'/'+p.total:'N/A'} · Pièces reçues : ${p.received} · vérifiées : 0 · validations : 0.</p>
 <details><summary>Documents ciblés</summary>${[...new Set(fields.flatMap(f=>f.sources.map(s=>s.model)))].map(m=>`<label><input type="checkbox" data-target="${m}" ${d.targets.includes(m)?'checked':''}>${esc(modelNames[m]||m)}</label>`).join('')}<p>Les contrôles fiscaux, sanctions et décisions restent réservés aux personnes habilitées. Catalogue FR opérationnel partiel ; inventaire FR/EN dans le rapport de couverture.</p></details>
 <label>Point à traiter <select id="fieldChoose">${fields.filter(f=>!f.restricted).map(f=>`<option value="${f.id}" ${selected===f.id?'selected':''}>${esc(f.label)} — ${esc(infoNames[state(d,f).info])}</option>`).join('')}</select></label>
 <p>${esc(f.question)}</p><p>Pourquoi : compléter ${f.sources.map(s=>esc(modelNames[s.model]||s.model)).join(', ')}. ${state(d,f).info==='conflict'?'Plusieurs déclarations se contredisent : demander une clarification.':''}</p>
 <button data-do="ask">Afficher cette question</button><button data-do="source">Voir source</button><button data-do="defer">Reporter</button><button data-do="unknown">Client ne sait pas</button><button data-do="unavailable">Document indisponible</button><button data-do="na">Non applicable</button><button data-do="reopen">Réouvrir</button><button data-do="voice">Corriger par la voix</button>
 ${d.actions[selected]?`<p>Suivi : ${esc(d.actions[selected].reason)} · Responsable : ${esc(d.actions[selected].owner||'à préciser')} · Échéance : ${esc(d.actions[selected].due||'à préciser')}</p>`:''}
 <label>Pièce client liée au point sélectionné <input id="evidenceFile" type="file" accept=".txt,.md,.pdf,.docx"></label><p>TXT/MD : contenu exploitable. PDF/DOCX : réception enregistrée, lecture manuelle requise ; aucun contenu prétendu extrait.</p>
 <details><summary>Faits et corrections (${d.facts.length})</summary>${d.facts.slice(-30).reverse().map(x=>`<div class="fact"><b>${esc(fields.find(f=>f.id===x.fieldId)?.label)}</b> : ${esc(x.raw)} ${x.superseded?'(historique)':''}<br>${esc(infoNames[state(d,fields.find(f=>f.id===x.fieldId)).info])} · « ${esc(x.quote)} »<br>Source : ${esc(x.sourceId)} · ${esc(x.role)}<button data-correct="${esc(x.id)}">Confirmer cette correction</button></div>`).join('')}</details>
 <details><summary>Pièces reçues (${d.evidence.length})</summary>${d.evidence.map(e=>`<p>${esc(e.filename)} — reçu, à examiner</p>`).join('')}</details>
 <details><summary>Points manquants (${needs(d).length})</summary>${needs(d).map(f=>`<p>${esc(f.label)}</p>`).join('')}</details>
 <button data-do="constraint">Ajouter une contrainte sourcée</button><details><summary>Contraintes et suivis</summary><pre>${esc(d.constraints.map(c=>c.type+' : '+c.cause+' — '+(c.owner||'responsable à préciser')+' — '+(c.due||'échéance à préciser')+' — source '+c.sourceId).join('\n'))}</pre></details>
 <button data-do="md">Exporter brouillons MD</button><button data-do="json">Sauvegarder JSON</button><button data-do="events">Exporter événements n8n</button><button data-do="snapshot">Figer un brouillon</button>
 <p>${d.snapshots.length} version(s) figée(s). Extraction : ${d.metrics.batches} lots, ${d.metrics.input} tokens entrants, ${d.metrics.output} sortants.</p>`:''}<p role="status">${esc(message)}</p>`;root.querySelectorAll('#dossierBody details').forEach((x,i)=>x.open=opened[i]||false);if(focus&&root.querySelector('#'+focus))root.querySelector('#'+focus).focus({preventScroll:true});}
root.addEventListener('click',async e=>{const d=current(),action=e.target.dataset.do;try{
 if(action==='new'){if(A.S.listening)throw new Error('Terminez l’appel avant de changer de dossier.');const name=await ask('Nom du dossier');if(name?.trim()){const n=createDossier(name.trim());db.items.push(n);db.active=n.id;A.resetDossierCall();save();}}
 if(!d)return;
 if(e.target.dataset.correct){if(await approve('Retenir cette déclaration comme correction ? Les précédentes resteront dans l’historique ; cela ne vérifie pas la déclaration.')){correct(d,e.target.dataset.correct);save();}}
 const f=fields.find(x=>x.id===selected);
 if(action==='ask'){A.showDossierQuestion(f);event(d,'question.displayed',{fieldId:f.id});save();}
 if(action==='source'){message=(f.sources.map(s=>`${s.model} · FR · §${s.section} · page ${s.page}`).join('\n')+'\nVersion et fichier exacts : docs/catalogue-modeles.json.');render();}
 if(['defer','unknown','unavailable','na'].includes(action)){const reason=await ask('Motif / cause (obligatoire)');if(reason?.trim()){const owner=await ask('Responsable du suivi (facultatif)')||'',due=await ask('Date du suivi, avec année (facultatif)')||'';defer(d,selected,{defer:'deferred',unknown:'unknown',unavailable:'unavailable',na:'not_applicable'}[action],reason,owner,due);save();}}
 if(action==='reopen'){delete d.actions[selected];event(d,'followup.reopened',{fieldId:selected});save();}
 if(action==='voice'){message='Dites la correction pendant l’enregistrement. Puis confirmez la nouvelle déclaration dans « Faits et corrections ». Aucun remplacement automatique.';render();}
 if(action==='md')download(d.name+'.md',exportMarkdown(d));
 if(action==='json')download(d.name+'.json',JSON.stringify(d,null,2),'application/json');
 if(action==='events')download(d.name+'-events.json',JSON.stringify({schema:1,events:d.events},null,2),'application/json');
 if(action==='snapshot'){d.snapshots.push({id:uid(),at:new Date().toISOString(),status:'draft',text:exportMarkdown(d)});event(d,'draft.snapshot',{});save();}
 if(action==='constraint'){const cause=await ask('Cause et conséquence concrètes'),sourceId=await ask('Identifiant d’une source du dossier');if(cause&&d.sources.some(s=>s.id===sourceId)){const type=await ask('Type : financier, calendrier, contractuel, juridique ou stratégique')||'à préciser';d.constraints.push({id:uid(),cause,sourceId,type,owner:await ask('Responsable')||'',due:await ask('Échéance')||'',flexibility:await ask('Flexibilité / action possible')||'',at:new Date().toISOString()});save();}else if(cause)throw new Error('Une source existante est nécessaire.');}
 }catch(err){message=err.message;render();}});
root.addEventListener('change',async e=>{try{const d=current();if(e.target.id==='dossierChoose'){if(A.S.listening)throw new Error('Terminez l’appel avant de changer de dossier.');db.active=e.target.value;A.resetDossierCall();A.restoreDossierCall(current()?.call);save();}
 if(e.target.id==='dossierStage'){d.stage=e.target.value;save();}
 if(e.target.id==='fieldChoose'){selected=e.target.value;render();}
 if(e.target.dataset.target){const m=e.target.dataset.target;d.targets=e.target.checked?[...new Set([...d.targets,m])]:d.targets.filter(x=>x!==m);save();}
 if(e.target.id==='dossierImport'){if(A.S.listening)throw new Error('Terminez l’appel avant l’import.');const file=e.target.files[0];if(file.size>5000000)throw new Error('Sauvegarde trop volumineuse.');const n=importDossier(await file.text());db.items.push(n);db.active=n.id;A.resetDossierCall();save();}
 if(e.target.id==='evidenceFile'){const file=e.target.files[0];if(file.size>10000000)throw new Error('Pièce trop volumineuse (10 Mo maximum).');const bytes=await file.arrayBuffer(),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');if(d.evidence.some(x=>x.hash===hash&&x.fieldId===selected))return;const id=uid();d.evidence.push({id,fieldId:selected,filename:file.name,hash,status:'received',at:new Date().toISOString()});if(/\.(txt|md)$/i.test(file.name))d.sources.push({id,text:new TextDecoder().decode(bytes).slice(0,16000),role:'document',filename:file.name});event(d,'evidence.received',{id,hash});save();}
 }catch(err){message=err.message;render();}});
window.dossierEnsure=()=>{if(!current()){const d=createDossier(A.S.cfg.contexte.slice(0,80)||'Nouveau dossier');db.items.push(d);db.active=d.id;save();}};
window.dossierSaveCall=call=>{const d=current();if(d){d.call=structuredClone(call);save();}};
window.dossierContext=()=>{const d=current();return d?{stage:d.stage,targets:d.targets,needs:needs(d,A.S.categorie).slice(0,8).map(f=>({fieldId:f.id,question:f.question,documents:f.sources,state:state(d,f)})),deferred:d.actions,declared:d.facts.filter(f=>!f.superseded).slice(-15).map(f=>({fieldId:f.fieldId,raw:f.raw,role:f.role}))}:null;};
window.dossierFinalSegment=(segment)=>{const d=current();if(!d)return;const role=A.whoOf(segment.sp),source={id:segment.id||uid(),text:segment.text,t:segment.t,role:role==='me'?'advisor':role==='them'?'client':'uncertain'};if(!d.sources.some(s=>s.id===source.id))d.sources.push(source);save();};
setInterval(async()=>{const d=current();if(!d||busy||Date.now()<retryAt||!A.S.password||!A.S.cfg.contexte)return;const sources=[];let chars=0;for(const s of d.sources.filter(s=>!d.processed.includes(s.id)&&s.role!=='advisor')){if(sources.length>=12||chars+s.text.length>30000)break;sources.push(s);chars+=s.text.length;}if(!sources.length)return;busy=true;try{const result=await A.api({mode:'extract',sources},null,AbortSignal.timeout(45000));ingest(d,result,sources);failures=0;retryAt=0;const u=result.usage||{};d.metrics.input+=u.input||0;d.metrics.output+=u.output||0;save();}catch(err){failures++;retryAt=Date.now()+Math.min(60000,6000*2**failures);message='Extraction différée : '+err.message+' · L’écoute continue.';render();}finally{busy=false;}},6000);
render();

if(current()?.call)A.restoreDossierCall(current().call);
