export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function api(action,body,query={}){const params=new URLSearchParams({action,...query});const r=await fetch('/api/platform?'+params,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({error:'Réponse illisible'}));if(!r.ok){if(r.status===401&&action!=='login')location.assign('/login');if(r.status===428)location.assign('/login?change=1');throw Object.assign(new Error(data.error||'Erreur récupérable'),{status:r.status});}return data;}
export async function downloadFile(file,dossierId){const parts=[];for(let i=0;i<file.parts;i++){const r=await fetch('/api/platform?'+new URLSearchParams({action:'file-part',dossierId,fileId:file.id,part:i}));if(!r.ok)throw new Error('Téléchargement refusé ou interrompu.');parts.push(await r.arrayBuffer());}return new Blob(parts,{type:file.mime});}
export function download(name,text,type='text/plain'){const u=URL.createObjectURL(text instanceof Blob?text:new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000);}
export async function upload(file,dossierId,{callId=null,kind='evidence',fieldId=null,audioGroup=null,audioOffset=0,fileId=crypto.randomUUID(),onProgress=()=>{}}={}){
 const size=2097152,parts=Math.ceil(file.size/size);const init=await api('file-init',{dossierId,fileId,filename:file.name||'audio.webm',mime:file.type||'application/octet-stream',parts,bytes:file.size,callId,kind,fieldId,audioGroup,audioOffset});const present=new Set(init.uploadedParts||[]);onProgress(present.size,parts);
 for(let i=0;i<parts;i++){if(present.has(i))continue;const r=await fetch('/api/platform?'+new URLSearchParams({action:'upload-part',dossierId,fileId,part:i}),{method:'POST',headers:{'content-type':'application/octet-stream'},body:file.slice(i*size,(i+1)*size)});if(!r.ok)throw Object.assign(new Error(r.status===401?'Session expirée : reconnectez-vous puis reprenez les envois.':'Envoi interrompu : copie locale à reprendre.'),{status:r.status});present.add(i);onProgress(present.size,parts);}
 await api('file-complete',{dossierId,fileId});return fileId;
}
export function status(text){const el=document.getElementById('status');if(el)el.textContent=text;}
export async function form(title,inputs){return new Promise(resolve=>{const d=document.createElement('dialog');d.innerHTML='<form method="dialog"><h2>'+esc(title)+'</h2>'+inputs.map(i=>'<label>'+esc(i.label)+(i.type==='textarea'?'<textarea name="'+esc(i.name)+'" '+(i.required?'required':'')+'>'+esc(i.value||'')+'</textarea>':i.options?'<select name="'+esc(i.name)+'" '+(i.required?'required':'')+' '+(i.multiple?'multiple':'')+'>'+i.options.map(o=>'<option value="'+esc(o.value)+'" '+((Array.isArray(i.value)?i.value.includes(o.value):i.value===o.value)?'selected':'')+'>'+esc(o.label)+'</option>').join('')+'</select>':'<input name="'+esc(i.name)+'" type="'+(i.type||'text')+'" value="'+esc(i.value||'')+'" '+(i.required?'required':'')+'>')+'</label>').join('')+'<p><button value="save">Enregistrer</button><button value="cancel" formnovalidate>Annuler</button></p></form>';document.body.append(d);for(const i of inputs.filter(i=>i.search)){const select=d.querySelector('[name="'+i.name+'"]'),search=document.createElement('input');search.type='search';search.placeholder='Rechercher…';search.setAttribute('aria-label','Rechercher : '+i.label);select.before(search);search.oninput=()=>{for(const option of select.options)option.hidden=!option.text.toLowerCase().includes(search.value.toLowerCase());};}d.addEventListener('close',()=>{const fd=new FormData(d.querySelector('form')),data=d.returnValue==='save'?Object.fromEntries(fd):null;if(data)for(const i of inputs.filter(i=>i.multiple))data[i.name]=fd.getAll(i.name);d.remove();resolve(data);});d.showModal();});}
export async function notice(title,text){const d=document.createElement('dialog');d.innerHTML='<h2>'+esc(title)+'</h2><pre>'+esc(text)+'</pre><form method="dialog"><button>Fermer</button></form>';document.body.append(d);d.addEventListener('close',()=>d.remove());d.showModal();}
export function secretNotice(userId,password){const d=document.createElement('dialog');d.innerHTML='<h2>Mot de passe temporaire individuel</h2><p>À communiquer personnellement. Son remplacement sera exigé à la première connexion. Il ne sera plus consultable après fermeture.</p><label>Mot de passe<input type="password" readonly autocomplete="off"></label><button data-show>Afficher</button><button data-copy>Copier</button><button data-renew>Régénérer et invalider le précédent</button><p role="status"></p><form method="dialog"><button>Fermer</button></form>';document.body.append(d);const input=d.querySelector('input');input.value=password;d.querySelector('[data-show]').onclick=()=>input.type=input.type==='password'?'text':'password';d.querySelector('[data-copy]').onclick=async()=>{try{await navigator.clipboard.writeText(input.value);d.querySelector('[role=status]').textContent='Copié.';}catch{d.querySelector('[role=status]').textContent='Sélectionnez et copiez manuellement le mot de passe.';}};d.querySelector('[data-renew]').onclick=async e=>{e.target.disabled=true;try{input.value=(await api('admin-reset',{userId})).temporaryPassword;d.querySelector('[role=status]').textContent='Le précédent mot de passe est invalidé.';}catch(e){d.querySelector('[role=status]').textContent=e.message;}finally{e.target.disabled=false;}};d.onclose=()=>{input.value='';d.remove();};d.showModal();}
export const roles={advisor:'Advisor',responsable:'Responsable',admin:'Admin'};
export function navigation(p){return '<nav>'+Object.keys(roles).filter(r=>p.roles.includes(r)).map(r=>'<a href="/'+r+'">'+roles[r]+'</a>').join('')+'<span>'+esc(p.name)+'</span><button id="logout">Déconnexion</button></nav>';}
