export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function api(action,body,query={}){const params=new URLSearchParams({action,...query});const r=await fetch('/api/platform?'+params,{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({error:'Réponse illisible'}));if(!r.ok){if(r.status===401&&action!=='login')location.assign('/login');if(r.status===428)location.assign('/login?change=1');throw Object.assign(new Error(data.error||'Erreur récupérable'),{status:r.status});}return data;}
export async function downloadFile(file,dossierId){const parts=[];for(let i=0;i<file.parts;i++){const r=await fetch('/api/platform?'+new URLSearchParams({action:'file-part',dossierId,fileId:file.id,part:i}));if(!r.ok)throw new Error('Téléchargement refusé ou interrompu.');parts.push(await r.arrayBuffer());}return new Blob(parts,{type:file.mime});}
export function download(name,text,type='text/plain'){const u=URL.createObjectURL(text instanceof Blob?text:new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000);}
export async function upload(file,dossierId,{callId=null,kind='evidence',fieldId=null,audioGroup=null,audioOffset=0,fileId=crypto.randomUUID()}={}){
 const size=2097152,parts=Math.ceil(file.size/size);const init=await api('file-init',{dossierId,fileId,filename:file.name||'audio.webm',mime:file.type||'application/octet-stream',parts,bytes:file.size,callId,kind,fieldId,audioGroup,audioOffset});if(init.receipt==='received')return fileId;
 for(let i=0;i<parts;i++){const r=await fetch('/api/platform?'+new URLSearchParams({action:'upload-part',dossierId,fileId,part:i}),{method:'POST',headers:{'content-type':'application/octet-stream'},body:file.slice(i*size,(i+1)*size)});if(!r.ok)throw new Error('Envoi interrompu : copie locale à reprendre.');}
 await api('file-complete',{dossierId,fileId});return fileId;
}
export function status(text){const el=document.getElementById('status');if(el)el.textContent=text;}
export async function form(title,inputs){return new Promise(resolve=>{const d=document.createElement('dialog');d.innerHTML='<form method="dialog"><h2>'+esc(title)+'</h2>'+inputs.map(i=>'<label>'+esc(i.label)+'<input name="'+esc(i.name)+'" type="'+(i.type||'text')+'" value="'+esc(i.value||'')+'" '+(i.required?'required':'')+'></label>').join('')+'<p><button value="save">Enregistrer</button><button value="cancel" formnovalidate>Annuler</button></p></form>';document.body.append(d);d.addEventListener('close',()=>{const data=d.returnValue==='save'?Object.fromEntries(new FormData(d.querySelector('form'))):null;d.remove();resolve(data);});d.showModal();});}
export async function notice(title,text){const d=document.createElement('dialog');d.innerHTML='<h2>'+esc(title)+'</h2><pre>'+esc(text)+'</pre><form method="dialog"><button>Fermer</button></form>';document.body.append(d);d.addEventListener('close',()=>d.remove());d.showModal();}
export const roles={advisor:'Advisor',responsable:'Responsable',admin:'Admin'};
export function navigation(p){return '<nav>'+Object.keys(roles).filter(r=>p.roles.includes(r)).map(r=>'<a href="/'+r+'">'+roles[r]+'</a>').join('')+'<span>'+esc(p.name)+'</span><button id="logout">Déconnexion</button></nav>';}
