import {api,esc,form,notice,downloadFile,download,upload,navigation,status,roles} from './platform-client.js';
const app=document.getElementById('app'),p=window.MEET_PROFILE;let current=null,details=null,listing=[],users=[];
const names={K09:'Évaluation préliminaire',K11:'Demande de pièces',K13:'Connaissance client',K15:'Conformité',K16:'Résidences fiscales',K17:'Diligences',A02:'Trésorerie',A06:'Sources et emplois',A07:'Résumé du projet',A10:'Risques'};
function error(e){status(e.message);}
function link(d,tab='overview'){return '/responsable/clients/'+d.client_id+'/dossiers/'+d.id+'/'+tab;}
async function login(){app.innerHTML='<section class="login"><h1>'+((p?.must_change_password)?'Activer votre compte':'Connexion')+'</h1><form id="login">'+(!p?.must_change_password?'<label>Email<input name="email" type="email" autocomplete="username" required></label>':'<p>Choisissez votre mot de passe personnel. Le mot de passe temporaire ne sera plus utilisable.</p>')+'<label>Mot de passe<input name="password" type="password" autocomplete="'+(p?.must_change_password?'new-password':'current-password')+'" minlength="'+(p?.must_change_password?14:1)+'" required></label><button>Se connecter</button></form><p class="muted">Accès individuel sur invitation interne. Aucune inscription publique.</p></section>';
 document.getElementById('login').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const data=Object.fromEntries(new FormData(e.target));await api(p?.must_change_password?'password':'login',data);location.assign('/');}catch(e){error(e);}finally{b.disabled=false;}};
}
function card(d){const next=Object.values(d.data.actions||{}).filter(a=>a.due).sort((a,b)=>a.due.localeCompare(b.due))[0];return '<article class="card" data-company="'+esc(d.society)+'"><h2>'+esc(d.name)+'</h2><p>'+esc(d.society)+' · '+esc(d.data.stage)+' · révision '+d.revision+'</p><p>Dernier échange : '+new Date(d.updated_at).toLocaleString('fr-FR')+'</p><p>Prochaine action : '+esc(next?next.reason+' — '+next.due:'À préciser')+'</p><div class="actions">'+(p.roles.includes('advisor')&&d.permissions.includes('call')?'<a class="button" href="/advisor?dossier='+d.id+'">Conduire un appel</a>':'')+(p.roles.includes('responsable')?'<a class="button" href="'+link(d)+'">Ouvrir le dossier</a>':'')+'</div></article>';}
async function dashboard(){const previous=Object.fromEntries(['search','company','member','stage','since','priority','metric'].map(id=>[id,document.getElementById(id)?.value||'']));const data=await api('list');listing=data.dossiers;const docs=Object.values(Object.fromEntries(data.documents.slice().reverse().map(d=>[d.dossier_id+':'+d.model,d])));const overdue=data.tasks.filter(t=>t.due&&t.due<new Date().toISOString().slice(0,10)&&t.status!=='Terminée');
 app.innerHTML='<h1>Suivi des clients</h1><div class="actions">'+(p.can_create?'<button data-action="create">Nouveau client / dossier</button>':'')+'<button data-action="refresh">Actualiser</button></div><div class="grid"><button data-metric="review">'+data.calls.filter(c=>c.status==='À revoir').length+' bilans à examiner</button><button data-metric="late">'+overdue.length+' actions en retard</button><button data-metric="partial">'+docs.filter(d=>d.completion.status==='Partiel').length+' documents partiels</button></div><div class="filters"><label>Client / projet<input id="search"></label><label>Société<select id="company"><option value="">Toutes</option><option>PWM</option><option>ADM</option></select></label><label>Advisor / responsable<select id="member"><option value="">Tous les membres affectés</option>'+data.members.map(m=>'<option value="'+m.id+'">'+esc(m.name)+' ('+esc(m.roles.join(', '))+')</option>').join('')+'</select></label><label>Étape<select id="stage"><option value="">Toutes</option><option value="qualification">Qualification</option><option value="documents">Documents</option><option value="approfondir">Approfondir</option></select></label><label>Depuis le<input type="date" id="since"></label><label>Priorité<select id="priority"><option value="">Toutes</option><option value="haute">Haute</option><option value="normal">Normale</option></select></label><label>Suivi<select id="metric"><option value="">Tous</option><option value="review">Bilans à examiner</option><option value="late">Actions en retard</option><option value="partial">Documents partiels</option></select></label></div><details><summary>Notifications internes ('+data.notifications.length+')</summary>'+data.notifications.map(n=>'<p><a href="'+link(listing.find(d=>d.id===n.dossier_id))+'">'+esc(listing.find(d=>d.id===n.dossier_id)?.name)+'</a> — '+esc(n.event)+' — '+new Date(n.created_at).toLocaleString('fr-FR')+'</p>').join('')+'</details><div class="grid" id="cards"></div>';
 const filter=()=>{const get=id=>document.getElementById(id).value;const visible=listing.filter(d=>{
  const q=get('search').toLowerCase(),c=get('company'),member=get('member'),stage=get('stage'),since=get('since'),priority=get('priority'),metric=get('metric');const client=data.clients.find(c=>c.id===d.client_id);
  return (!q||(d.name+' '+client?.name).toLowerCase().includes(q))&&(!c||d.society===c)&&(!member||data.grants.some(g=>g.dossier_id===d.id&&g.user_id===member))&&(!stage||d.data.stage===stage)&&(!since||d.updated_at.slice(0,10)>=since)&&(!priority||data.tasks.some(t=>t.dossier_id===d.id&&t.priority===priority))&&(!metric||(metric==='review'&&data.calls.some(c=>c.dossier_id===d.id&&c.status==='À revoir'))||(metric==='late'&&overdue.some(t=>t.dossier_id===d.id))||(metric==='partial'&&docs.some(x=>x.dossier_id===d.id&&x.completion.status==='Partiel')));
 });document.getElementById('cards').innerHTML=visible.map(card).join('')||'<section>Aucun dossier correspondant dans votre périmètre.</section>';};for(const id of ['search','company','member','stage','since','priority','metric'])document.getElementById(id).addEventListener('input',filter);app.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{document.getElementById('metric').value=b.dataset.metric;filter();});for(const [id,value]of Object.entries(previous))document.getElementById(id).value=value;filter();
}
async function dossier(id,tab){details=await api('detail',null,{dossierId:id});current=details.dossier;const d=current,data=d.data;
 if(location.pathname.split('/')[3]!==d.client_id)throw new Error('Le client du lien ne correspond pas au dossier.');
 const latest=Object.values(Object.fromEntries(details.documents.map(doc=>[doc.model,doc]).reverse()));
 app.innerHTML='<a href="/responsable">← Dossiers autorisés</a><h1>'+esc(d.name)+'</h1><p>'+esc(d.society)+' · révision '+d.revision+'</p><div class="tabs">'+[['overview','Vue d’ensemble'],['calls','Appels'],['facts','Bilan et faits'],['actions','Actions'],['constraints','Contraintes'],['data-room','Data room'],['history','Historique']].map(([v,l])=>'<a href="'+link(d,v)+'">'+l+'</a>').join('')+'</div><div class="actions"><button data-action="refresh">Actualiser</button><button data-action="export">Export Markdown</button><button data-action="events">Événements n8n</button><button data-action="transfer">Transfert PWM → Admiralty</button></div><div id="view"></div>';
 const view=document.getElementById('view');
 if(tab==='data-room'){
  view.innerHTML='<section><h2>Pièces reçues et versions générées</h2><label>Recherche<input id="docSearch"></label><label>Ajouter une pièce au dossier choisi<input id="upload" type="file" accept=".pdf,.docx,.txt,.md,.png,.jpg,.jpeg"></label><p class="muted">Stockage privé. Les pièces reçues ne sont pas vérifiées automatiquement. Un document complet reste à relire.</p></section><div id="documents">'+latest.map(doc=>'<section class="doc"><h3>'+esc(names[doc.model]||doc.model)+'</h3><small>Version documentaire '+esc(doc.id)+'</small><p><span class="badge">'+esc(doc.completion.status)+'</span><span class="badge">'+esc(doc.review)+'</span><span class="badge">'+esc(doc.technical)+'</span></p><p>'+esc(doc.completion.scope)+' · '+doc.completion.filled+'/'+doc.completion.total+' rubriques déclarées · Version '+doc.version+' · Faits r'+doc.source_revision+(doc.source_revision!==d.revision?' — vérifier les changements ultérieurs':'')+'</p><details><summary>Rubriques et points manquants</summary>'+doc.completion.fields.map(f=>'<p>'+esc(f.label)+' : '+esc(f.info)+' · '+esc(f.applicability)+'</p>').join('')+'</details><details><summary>Aperçu sourcé</summary><pre>'+esc(doc.content)+'</pre></details><div class="actions"><button data-doc="'+doc.id+'">Télécharger MD</button><button data-review="'+doc.id+'">Revue</button></div><details><summary>Historique des versions</summary>'+details.documents.filter(x=>x.model===doc.model).map(x=>'<p>Version '+x.version+' — '+esc(x.review)+' — faits r'+x.source_revision+' <button data-doc="'+x.id+'">Voir / télécharger</button></p>').join('')+'</details></section>').join('')+details.files.filter(f=>f.kind==='evidence').map(f=>'<section class="doc"><h3>'+esc(f.filename)+'</h3><small>Référence '+esc(f.id)+'</small><p>'+esc(f.family)+' · '+esc(f.receipt)+' · '+esc(f.exploitability)+' · '+esc(f.verification)+'</p><button data-file="'+f.id+'" '+(f.receipt!=='received'?'disabled':'')+'>Télécharger la source</button></section>').join('')+'</div>';
  document.getElementById('docSearch').oninput=e=>view.querySelectorAll('.doc').forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(e.target.value.toLowerCase()));document.getElementById('upload').onchange=async e=>{try{status('Envoi de la pièce…');await upload(e.target.files[0],d.id);await dossier(d.id,tab);status('Pièce sauvegardée ; traitement en attente.');}catch(e){error(e);}};
 }else if(tab==='calls')view.innerHTML=details.calls.map(c=>'<section><h2>Appel du '+new Date(c.started_at).toLocaleString('fr-FR')+'</h2><p>'+esc(c.status)+' · '+esc(c.audio_status)+' · '+Math.round(c.duration_ms/60000)+' min</p><p>Advisor : '+esc(c.advisor_id||c.historical_author||'Attribution à confirmer')+'</p><button data-call="'+c.id+'">Transcription, audio et bilan</button></section>').join('')||'<section>Aucun appel conservé.</section>';
 else if(tab==='facts')view.innerHTML='<section><h2>Déclarations et corrections</h2>'+data.facts.map(f=>'<article class="card"><b>'+esc(f.fieldId)+'</b> : '+esc(f.raw)+(f.superseded?' (historique)':'')+'<blockquote>'+esc(f.quote)+'</blockquote><small>Fait '+esc(f.id)+' · Source '+esc(f.sourceId)+' · '+esc(f.role)+'</small><p><button data-correct="'+f.id+'">Retenir comme correction</button></p></article>').join('')+'</section>';
 else if(tab==='actions')view.innerHTML='<section><h2>Actions du dossier</h2><button data-action="task">Ajouter une action</button>'+details.tasks.map(t=>'<article class="card"><b>'+esc(t.title)+'</b><p>'+esc(t.status)+' · '+esc(t.due||'Échéance à préciser')+' · '+esc(t.owner_id||'Responsable à confirmer')+'</p><button data-task="'+t.id+'">Modifier le statut</button></article>').join('')+'<h3>Pièces / réponses différées</h3>'+Object.entries(data.actions).map(([f,a])=>'<p>'+esc(f)+' : '+esc(a.reason)+' · '+esc(a.owner)+' · '+esc(a.due)+'</p>').join('')+'</section>';
 else if(tab==='constraints')view.innerHTML='<section><h2>Contraintes</h2>'+data.constraints.map(c=>'<p>'+esc(c.type)+' : '+esc(c.cause)+' — '+esc(c.owner)+' — '+esc(c.due)+' — source '+esc(c.sourceId)+'</p>').join('')+'</section>';
 else if(tab==='history')view.innerHTML='<section><h2>Historique des changements</h2>'+details.audit.map(e=>'<p>'+new Date(e.created_at).toLocaleString('fr-FR')+' · '+esc(e.event)+' · '+esc(e.actor_id||'Traitement serveur')+'</p>').join('')+'</section>';
 else view.innerHTML='<section><h2>Vue d’ensemble</h2><p>Objectif : '+esc(data.stage)+'</p><p>'+data.facts.filter(f=>!f.superseded).length+' faits conservés · '+details.calls.length+' appels · '+latest.length+' brouillons</p><p>Équipe affectée : '+details.grants.map(g=>esc(g.user_id)).join(', ')+'</p><p>Identifiant dossier : '+esc(d.id)+'</p></section><section><h2>Traitements</h2>'+details.jobs.map(j=>'<p>'+esc(j.kind)+' · '+esc(j.status)+(j.last_error?' — '+esc(j.last_error):'')+(j.status==='failed'?'<button data-retry="'+j.id+'">Relancer</button>':'')+'</p>').join('')+'</section>';
}
async function showCall(id){const result=await api('call',null,{dossierId:current.id,callId:id});const audio=details.files.filter(f=>f.call_id===id&&f.kind==='audio'&&f.receipt==='received').sort((a,b)=>a.filename.localeCompare(b.filename));
 const groups=[...new Set(audio.map(f=>f.audio_group||'initial'))];const dialog=document.createElement('dialog');dialog.innerHTML='<h2>Appel — '+esc(result.call.status)+'</h2><p>Audio : '+esc(result.call.audio_status)+' ; transcription : '+esc(result.call.transcript_status)+'</p><label>Séquence audio<select id="audioGroup">'+groups.map((g,i)=>'<option value="'+esc(g)+'">Séquence '+(i+1)+'</option>').join('')+'</select></label><button id="loadAudio" '+(!audio.length?'disabled':'')+'>Charger l’audio sauvegardé</button><audio controls id="player"></audio><label>Rechercher dans la transcription<input id="transcriptSearch"></label><div id="segments">'+result.segments.map(s=>'<p data-text="'+esc(s.text.toLowerCase())+'"><button data-seek="'+s.position_ms+'">'+Math.floor(s.position_ms/60000)+':'+String(Math.floor(s.position_ms/1000)%60).padStart(2,'0')+'</button> ['+esc(s.role)+'] '+esc(s.text)+'</p>').join('')+'</div><h3>Bilan préparé automatiquement — à revoir</h3><pre>'+esc(result.call.summary||'Traitement en attente ou en erreur ; consulter le dossier.')+'</pre><form method="dialog"><button>Fermer</button></form>';document.body.append(dialog);let audioURL;
 dialog.querySelector('#loadAudio').onclick=async e=>{e.target.disabled=true;try{const selected=audio.filter(f=>(f.audio_group||'initial')===dialog.querySelector('#audioGroup').value),chunks=[];for(const f of selected)chunks.push(await downloadFile(f,current.id));if(audioURL)URL.revokeObjectURL(audioURL);audioURL=URL.createObjectURL(new Blob(chunks,{type:selected[0].mime}));dialog.querySelector('#player').src=audioURL;}catch(e){error(e);}finally{e.target.disabled=false;}};
 dialog.querySelector('#transcriptSearch').oninput=e=>dialog.querySelectorAll('[data-text]').forEach(x=>x.hidden=!x.dataset.text.includes(e.target.value.toLowerCase()));dialog.onclick=e=>{if(e.target.dataset.seek){const selected=audio.find(f=>(f.audio_group||'initial')===dialog.querySelector('#audioGroup').value);dialog.querySelector('#player').currentTime=Math.max(0,(Number(e.target.dataset.seek)-(selected?.audio_offset_ms||0))/1000);}};dialog.onclose=()=>{if(audioURL)URL.revokeObjectURL(audioURL);dialog.remove();};dialog.showModal();
}
async function admin(){const data=await api('admin-users');users=data.users;app.innerHTML='<h1>Administration des accès</h1><p>Admin seul ne permet pas de consulter les dossiers ni de conduire un appel. L’affectation et la société autorisée restent nécessaires.</p><button data-action="user-create">Créer un compte</button><div class="grid">'+users.map(u=>'<article class="card"><h2>'+esc(u.name)+'</h2><p>'+esc(u.email)+'</p><p>'+esc(u.roles.join(', '))+' · '+esc(u.societies.join(', '))+' · '+(u.active?'Actif':'Désactivé')+'</p>'+(u.id===p.id?'<p>Votre compte : modification des droits interdite.</p>':'<div class="actions"><button data-access="'+u.id+'">Droits</button><button data-reset="'+u.id+'">Réinitialiser</button><button data-revoke="'+u.id+'">Révoquer sessions</button><button data-grant="'+u.id+'">Affecter un dossier</button></div>')+'</article>').join('')+'</div><section><h2>Journal administratif</h2>'+data.audit.map(a=>'<p>'+esc(a.event)+' · '+new Date(a.created_at).toLocaleString('fr-FR')+'</p>').join('')+'</section>';}
document.addEventListener('click',async e=>{const t=e.target;try{
 if(t.id==='logout'){await api('logout',{});location.assign('/login');return;}
 if(t.dataset.action==='refresh'){await route();status('Actualisé.');}
 if(t.dataset.action==='create'){const input=await form('Nouveau client / dossier',[{name:'name',label:'Nom du client / projet',required:true},{name:'society',label:'Société : PWM ou ADM',value:p.societies[0],required:true},{name:'clientId',label:'Client existant : identifiant exact (facultatif)'}]);if(input){if(listing.some(d=>d.name.toLowerCase()===input.name.toLowerCase()))await notice('Doublon possible','Un dossier de même nom existe. Aucun rapprochement automatique ne sera effectué. Annulez la création si ce dossier correspond au même projet.');const d=await api('create',input);location.assign(p.roles.includes('responsable')?link(d):'/advisor?dossier='+d.id);}}
 if(t.dataset.action==='export')location.assign('/api/platform?'+new URLSearchParams({action:'export',dossierId:current.id}));
 if(t.dataset.action==='events')download('evenements.json',JSON.stringify(await api('events',null,{dossierId:current.id}),null,2),'application/json');
 if(t.dataset.doc){const {document:doc}=await api('document',null,{dossierId:current.id,documentId:t.dataset.doc});download((names[doc.model]||doc.model)+'-v'+doc.version+'.md',doc.content,'text/markdown');}
 if(t.dataset.file){status('Téléchargement autorisé…');const f=details.files.find(x=>x.id===t.dataset.file);download(f.filename,await downloadFile(f,current.id));status('Téléchargement terminé.');}
 if(t.dataset.call)await showCall(t.dataset.call);
 if(t.dataset.correct){const x=await form('Confirmer la correction',[{name:'confirmation',label:'Saisir CONFIRMER pour conserver ce fait et archiver les autres déclarations de la rubrique',required:true}]);if(x?.confirmation==='CONFIRMER'){await api('command',{dossierId:current.id,revision:current.revision,command:'correct',factId:t.dataset.correct});await route();}}
 if(t.dataset.review){const input=await form('Revue documentaire',[{name:'status',label:'État : En revue / À relire / Validé par une personne habilitée',value:'En revue',required:true},{name:'reason',label:'Motif et périmètre de la revue',required:true}]);if(input){await api('review',{...input,dossierId:current.id,documentId:t.dataset.review});await route();}}
 if(t.dataset.action==='task'){const input=await form('Action — à confirmer',[{name:'title',label:'Action',required:true},{name:'ownerId',label:'Identifiant du responsable affecté (facultatif)'},{name:'due',label:'Échéance',type:'date'},{name:'sourceId',label:'Référence source'}]);if(input){await api('task',{...input,dossierId:current.id});await route();}}
 if(t.dataset.task){const input=await form('Statut de l’action',[{name:'status',label:'À confirmer / Ouverte / En cours / Terminée',required:true}]);if(input){await api('task',{...input,dossierId:current.id,taskId:t.dataset.task});await route();}}
 if(t.dataset.action==='transfer'){const v=await form('Pack explicitement transféré',[{name:'targetId',label:'Identifiant du dossier Admiralty destinataire',required:true},{name:'factIds',label:'Identifiants des faits sélectionnés (séparés par virgules)'},{name:'fileIds',label:'Identifiants des fichiers sélectionnés (séparés par virgules)'},{name:'documentIds',label:'Identifiants des versions documentaires sélectionnées (séparés par virgules)'},{name:'reason',label:'Motif du transfert',required:true}]);if(v){await api('transfer',{...v,dossierId:current.id,...Object.fromEntries(['factIds','fileIds','documentIds'].map(k=>[k,v[k].split(',').map(x=>x.trim()).filter(Boolean)]))});status('Pack transféré ; les autres dossiers restent inchangés.');}}
 if(t.dataset.retry){await api('retry',{dossierId:current.id,jobId:t.dataset.retry});await route();}
 if(t.dataset.action==='user-create'){const input=await form('Créer un compte individuel',[{name:'name',label:'Nom',required:true},{name:'email',label:'Email',type:'email',required:true}]);if(input){const result=await api('admin-create',input);await admin();await notice('Mot de passe temporaire — affichage unique',result.temporaryPassword+'\nÀ transmettre personnellement au destinataire. Aucun email automatique envoyé.');}}
 if(t.dataset.access){const u=users.find(u=>u.id===t.dataset.access),input=await form('Droits du compte',[{name:'roles',label:'Rôles séparés par virgules : advisor,responsable,admin',value:u.roles.join(',')},{name:'societies',label:'Sociétés séparées par virgules : PWM,ADM',value:u.societies.join(',')},{name:'active',label:'Compte actif : oui/non',value:u.active?'oui':'non'},{name:'canCreate',label:'Créer des dossiers : oui/non',value:u.can_create?'oui':'non'}]);if(input){await api('admin-access',{userId:u.id,roles:input.roles.split(',').map(x=>x.trim()).filter(Boolean),societies:input.societies.split(',').map(x=>x.trim()).filter(Boolean),active:input.active==='oui',canCreate:input.canCreate==='oui'});await admin();}}
 if(t.dataset.reset){const input=await form('Réinitialiser l’accès',[{name:'confirm',label:'Saisir RESET : toutes les sessions seront révoquées',required:true}]);if(input?.confirm==='RESET'){const result=await api('admin-reset',{userId:t.dataset.reset});await notice('Mot de passe temporaire — affichage unique',result.temporaryPassword);}}
 if(t.dataset.revoke){await api('admin-revoke',{userId:t.dataset.revoke});status('Sessions révoquées.');}
 if(t.dataset.grant){const input=await form('Affectation explicite',[{name:'dossierId',label:'Identifiant exact du dossier',required:true},{name:'permissions',label:'Permissions séparées par virgules : read,write,call,assign,review,approve,transfer',value:'read',required:true}]);if(input){await api('admin-grant',{userId:t.dataset.grant,dossierId:input.dossierId,permissions:input.permissions.split(',').map(x=>x.trim()).filter(Boolean)});status('Affectation enregistrée.');}}
 }catch(e){error(e);}});
async function route(){if(location.pathname==='/login')return login();document.getElementById('header').innerHTML=navigation(p);if(location.pathname==='/admin')return admin();const match=location.pathname.match(/^\/responsable\/clients\/([a-f0-9-]+)\/dossiers\/([a-f0-9-]+)\/([a-z-]+)$/);if(match)return dossier(match[2],match[3]);if(location.pathname==='/spaces'){app.innerHTML='<h1>Choisir un espace</h1><div class="grid">'+p.roles.map(r=>'<a class="card" href="/'+r+'">'+esc(roles[r])+'</a>').join('')+'</div>';return;}return dashboard();}
route().catch(error);

let refreshing=false;
setInterval(async()=>{if(location.pathname!=='/responsable'||document.hidden||document.querySelector('dialog[open]')||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName)||refreshing)return;refreshing=true;try{await dashboard();}catch(e){error(e);}finally{refreshing=false;}},30000);


